import LedgerEntry from '../models/LedgerEntry.js';
import Account from '../models/Account.js';
import { seedStoreAccounts } from '../services/seedStoreAccounts.js';

async function push(entry, session) {
  await LedgerEntry.create([{ ...entry }], { session });
}

// Resolve a well-known account in the Chart of Accounts by name. Stores
// created through any of the onboarding flows are seeded up-front. The
// self-heal block below covers stores that pre-date the seeding being
// wired into store-creation — first ledger touch repairs the chart.
const CACHED_BY_STORE = new Map(); // storeId -> { accountName -> accountId }

async function resolveAccount(storeId, name, session) {
  const key = String(storeId);
  if (!CACHED_BY_STORE.has(key)) CACHED_BY_STORE.set(key, new Map());
  const cache = CACHED_BY_STORE.get(key);
  if (cache.has(name)) return cache.get(name);

  let a = await Account.findOne({ storeId, name }).session(session || null).lean();
  if (!a) {
    // Self-heal: the store doesn't have its chart of accounts yet (created
    // before seeding was wired into the onboarding flows). Seed now and
    // retry the lookup. Idempotent — seeds only what's missing.
    //
    // We deliberately seed OUTSIDE the calling transaction. Mongo can't
    // insert into a collection inside a session if the collection doesn't
    // exist yet (the implicit-create needs a separate transaction), and
    // the new account docs are seed data — committing them independently
    // of the user-triggered transaction is the right semantic.
    console.warn(
      `[ledger] Self-heal: store ${storeId} missing account "${name}". Seeding chart of accounts now.`,
    );
    try {
      await seedStoreAccounts(storeId);
    } catch (err) {
      console.error('[ledger] Self-heal seedStoreAccounts failed:', err?.stack || err);
    }
    a = await Account.findOne({ storeId, name }).session(session || null).lean();
    if (!a) {
      throw new Error(
        `[ledger] Chart-of-accounts account "${name}" not found for store ${storeId} even after self-heal.`,
      );
    }
  }
  cache.set(name, a._id);
  return a._id;
}

/** Map a payment mode to its ledger account name. Digital tenders land in
 *  Bank; physical cash in Cash. Keeps the books able to distinguish the two. */
function accountNameForMode(mode) {
  return mode === 'bank' || mode === 'upi' || mode === 'card' || mode === 'wallet'
    ? 'Bank'
    : 'Cash';
}

/** Resolve the Cash or Bank chart account for a given payment mode. */
async function resolveCashOrBank(storeId, mode, session) {
  return resolveAccount(storeId, accountNameForMode(mode), session);
}

export const LedgerEngine = {
  async recordSale(sale, { createdBy, session }) {
    const round2 = (n) => Math.round(n * 100) / 100;
    // Split tenders into cash vs bank vs credit by their actual mode —
    // previously every non-credit tender (incl. UPI/card) was posted to
    // the Cash account, so the books couldn't tell physical cash from
    // bank money. Now: cash → Cash A/c, upi/card/wallet → Bank A/c,
    // anything else (or the unpaid remainder) → receivable.
    let cashAmt = 0;
    let bankAmt = 0;
    for (const p of sale.payments || []) {
      const amt = Number(p.amount || 0);
      if (amt <= 0) continue;
      if (p.mode === 'cash') cashAmt += amt;
      else if (p.mode === 'upi' || p.mode === 'card' || p.mode === 'wallet') bankAmt += amt;
    }
    cashAmt = round2(cashAmt);
    bankAmt = round2(bankAmt);

    // Guard against cash overpayment (tendered > total → change given in
    // cash). The change never hits the ledger, so trim the cash bucket
    // down to what was actually settled.
    const settledDigitalCash = round2(cashAmt + bankAmt);
    if (settledDigitalCash > sale.grandTotal) {
      const excess = round2(settledDigitalCash - sale.grandTotal);
      cashAmt = round2(Math.max(0, cashAmt - excess));
    }

    const creditPortion = round2(Math.max(0, sale.grandTotal - cashAmt - bankAmt));
    const revenue = Number((sale.grandTotal - sale.totalTax).toFixed(2));

    if (cashAmt > 0) {
      const cashAccId = await resolveAccount(sale.storeId, 'Cash', session);
      await push(
        {
          storeId: sale.storeId,
          entryType: 'debit',
          accountType: 'cash',
          accountId: cashAccId,
          amount: cashAmt,
          referenceType: 'sale',
          referenceId: sale._id,
          narration: `Cash received for ${sale.invoiceNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
    if (bankAmt > 0) {
      const bankAccId = await resolveAccount(sale.storeId, 'Bank', session);
      await push(
        {
          storeId: sale.storeId,
          entryType: 'debit',
          accountType: 'bank',
          accountId: bankAccId,
          amount: bankAmt,
          referenceType: 'sale',
          referenceId: sale._id,
          narration: `Bank/UPI/card received for ${sale.invoiceNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
    if (creditPortion > 0) {
      // Per-party ledger: use the customer's _id as accountId so
      // /customers/:id/ledger picks this up. Trial balance still
      // groups it under "Sundry Debtors" via the resolveAccount
      // helper that maps `accountType: 'receivable'` → control
      // account. Falls back to the Sundry Debtors chart account when
      // there's no linked customer (walk-in credit sale, edge case).
      const fallbackAccId = await resolveAccount(sale.storeId, 'Sundry Debtors', session);
      await push(
        {
          storeId: sale.storeId,
          entryType: 'debit',
          accountType: 'receivable',
          accountId: sale.customerId || fallbackAccId,
          amount: creditPortion,
          referenceType: 'sale',
          referenceId: sale._id,
          narration: `Credit sale ${sale.invoiceNumber} to ${sale.customerSnapshot?.name || 'customer'}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }

    const salesAccId = await resolveAccount(sale.storeId, 'Sales Revenue', session);
    await push(
      {
        storeId: sale.storeId,
        entryType: 'credit',
        accountType: 'revenue',
        accountId: salesAccId,
        amount: revenue,
        referenceType: 'sale',
        referenceId: sale._id,
        narration: `Sales revenue ${sale.invoiceNumber}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );

    if (sale.totalTax > 0) {
      const gstOutAccId = await resolveAccount(sale.storeId, 'GST Payable (Output)', session);
      await push(
        {
          storeId: sale.storeId,
          entryType: 'credit',
          accountType: 'gst',
          accountId: gstOutAccId,
          amount: sale.totalTax,
          referenceType: 'sale',
          referenceId: sale._id,
          narration: `Output GST ${sale.invoiceNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
  },

  // Purchase GRN: Debit Purchase (expense) + Debit Input GST (asset), Credit Supplier Payable.
  async recordPurchaseReceipt(
    { storeId, supplierId, purchaseId, grnNumber, subtotal, totalTax, grandTotal, createdBy },
    { session } = {},
  ) {
    const purchaseAccId = await resolveAccount(storeId, 'Purchase Expense', session);
    await push(
      {
        storeId,
        entryType: 'debit',
        accountType: 'expense',
        accountId: purchaseAccId,
        amount: subtotal,
        referenceType: 'purchase',
        referenceId: purchaseId,
        narration: `Purchase ${grnNumber}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
    if (totalTax > 0) {
      const inputGstAccId = await resolveAccount(storeId, 'GST Input Credit', session);
      await push(
        {
          storeId,
          entryType: 'debit',
          accountType: 'gst',
          accountId: inputGstAccId,
          amount: totalTax,
          referenceType: 'purchase',
          referenceId: purchaseId,
          narration: `Input GST credit ${grnNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
    // Supplier payable: use the supplierId directly as accountId so lookups by
    // supplier work (/suppliers/:id/ledger filters by accountId).
    await push(
      {
        storeId,
        entryType: 'credit',
        accountType: 'payable',
        accountId: supplierId,
        amount: grandTotal,
        referenceType: 'purchase',
        referenceId: purchaseId,
        narration: `Payable to supplier ${grnNumber}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
  },

  /**
   * Record a customer payment against an existing credit / partial sale.
   * Dr Cash / Bank, Cr Sundry Debtors. referenceType='payment' so the trail is
   * distinguishable from the original sale entries in the day book.
   */
  async recordSalePayment(
    { storeId, saleId, invoiceNumber, customerName, amount, mode, reference, createdBy },
    { session } = {},
  ) {
    const isBank = mode === 'bank' || mode === 'upi' || mode === 'card' || mode === 'wallet';
    const cashOrBankAccId = await resolveCashOrBank(storeId, mode, session);
    await push(
      {
        storeId,
        entryType: 'debit',
        accountType: isBank ? 'bank' : 'cash',
        accountId: cashOrBankAccId,
        amount,
        referenceType: 'payment',
        referenceId: saleId,
        narration: `${isBank ? 'Bank' : 'Cash'} received against ${invoiceNumber}${reference ? ' ref ' + reference : ''}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
    const debtorsAccId = await resolveAccount(storeId, 'Sundry Debtors', session);
    await push(
      {
        storeId,
        entryType: 'credit',
        accountType: 'receivable',
        accountId: debtorsAccId,
        amount,
        referenceType: 'payment',
        referenceId: saleId,
        narration: `Settlement against ${invoiceNumber} from ${customerName || 'customer'}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
  },

  async recordPurchasePayment(
    { storeId, supplierId, purchaseId, amount, mode, reference, createdBy },
    { session } = {},
  ) {
    await push(
      {
        storeId,
        entryType: 'debit',
        accountType: 'payable',
        accountId: supplierId,
        amount,
        referenceType: 'payment',
        referenceId: purchaseId,
        narration: `Supplier payment (${mode})${reference ? ' ref ' + reference : ''}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
    const isBank = mode === 'bank' || mode === 'upi' || mode === 'card' || mode === 'wallet';
    const cashOrBankAccId = await resolveCashOrBank(storeId, mode, session);
    await push(
      {
        storeId,
        entryType: 'credit',
        accountType: isBank ? 'bank' : 'cash',
        accountId: cashOrBankAccId,
        amount,
        referenceType: 'payment',
        referenceId: purchaseId,
        narration: `${isBank ? 'Bank' : 'Cash'} outflow for supplier payment${reference ? ' ref ' + reference : ''}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
  },

  /**
   * Reverse a sale (Credit Note). Posts entries that exactly undo the original
   * sale's ledger impact, but tagged referenceType='return' so the voucher
   * trail is clear in the day book.
   */
  async recordSaleReturn(returnSale, { createdBy, session }) {
    const round2 = (n) => Math.round(n * 100) / 100;
    // Mirror the cash/bank split used on the original sale so the refund
    // flows OUT of the same account the money came IN to.
    let cashAmt = 0;
    let bankAmt = 0;
    for (const p of returnSale.payments || []) {
      const amt = Number(p.amount || 0);
      if (amt <= 0) continue;
      if (p.mode === 'cash') cashAmt += amt;
      else if (p.mode === 'upi' || p.mode === 'card' || p.mode === 'wallet') bankAmt += amt;
    }
    cashAmt = round2(cashAmt);
    bankAmt = round2(bankAmt);
    const settledDigitalCash = round2(cashAmt + bankAmt);
    if (settledDigitalCash > returnSale.grandTotal) {
      const excess = round2(settledDigitalCash - returnSale.grandTotal);
      cashAmt = round2(Math.max(0, cashAmt - excess));
    }
    const creditPortion = round2(Math.max(0, returnSale.grandTotal - cashAmt - bankAmt));
    const revenue = Number((returnSale.grandTotal - returnSale.totalTax).toFixed(2));

    if (cashAmt > 0) {
      const accId = await resolveAccount(returnSale.storeId, 'Cash', session);
      await push(
        {
          storeId: returnSale.storeId,
          entryType: 'credit', // refund — cash flows OUT
          accountType: 'cash',
          accountId: accId,
          amount: cashAmt,
          referenceType: 'return',
          referenceId: returnSale._id,
          narration: `Cash refund issued for ${returnSale.invoiceNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
    if (bankAmt > 0) {
      const accId = await resolveAccount(returnSale.storeId, 'Bank', session);
      await push(
        {
          storeId: returnSale.storeId,
          entryType: 'credit', // refund — bank money flows OUT
          accountType: 'bank',
          accountId: accId,
          amount: bankAmt,
          referenceType: 'return',
          referenceId: returnSale._id,
          narration: `Bank/UPI/card refund for ${returnSale.invoiceNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
    if (creditPortion > 0) {
      const accId = await resolveAccount(returnSale.storeId, 'Sundry Debtors', session);
      await push(
        {
          storeId: returnSale.storeId,
          entryType: 'credit', // reduces what customer owes
          accountType: 'receivable',
          accountId: accId,
          amount: creditPortion,
          referenceType: 'return',
          referenceId: returnSale._id,
          narration: `Credit note ${returnSale.invoiceNumber} → ${returnSale.customerSnapshot?.name || 'customer'}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }

    const salesAccId = await resolveAccount(returnSale.storeId, 'Sales Revenue', session);
    await push(
      {
        storeId: returnSale.storeId,
        entryType: 'debit', // reverses original credit
        accountType: 'revenue',
        accountId: salesAccId,
        amount: revenue,
        referenceType: 'return',
        referenceId: returnSale._id,
        narration: `Sales reversal ${returnSale.invoiceNumber}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );

    if (returnSale.totalTax > 0) {
      const gstOutAccId = await resolveAccount(returnSale.storeId, 'GST Payable (Output)', session);
      await push(
        {
          storeId: returnSale.storeId,
          entryType: 'debit', // reduces output GST liability
          accountType: 'gst',
          accountId: gstOutAccId,
          amount: returnSale.totalTax,
          referenceType: 'return',
          referenceId: returnSale._id,
          narration: `Output GST reversal ${returnSale.invoiceNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
  },

  /**
   * Reverse a purchase (Debit Note). Mirrors recordPurchaseReceipt but with
   * entry types flipped — Cr Purchase Expense, Cr Input GST, Dr Sundry Creditors.
   */
  async recordPurchaseReturn(
    { storeId, supplierId, purchaseId, dnNumber, subtotal, totalTax, grandTotal, createdBy },
    { session } = {},
  ) {
    const purchaseAccId = await resolveAccount(storeId, 'Purchase Expense', session);
    await push(
      {
        storeId,
        entryType: 'credit', // reverses original debit
        accountType: 'expense',
        accountId: purchaseAccId,
        amount: subtotal,
        referenceType: 'return',
        referenceId: purchaseId,
        narration: `Purchase return ${dnNumber}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
    if (totalTax > 0) {
      const inputGstAccId = await resolveAccount(storeId, 'GST Input Credit', session);
      await push(
        {
          storeId,
          entryType: 'credit', // reverses ITC claimed
          accountType: 'gst',
          accountId: inputGstAccId,
          amount: totalTax,
          referenceType: 'return',
          referenceId: purchaseId,
          narration: `Input GST reversal ${dnNumber}`,
          isAutoGenerated: true,
          createdBy,
        },
        session,
      );
    }
    await push(
      {
        storeId,
        entryType: 'debit', // reduces what we owe supplier
        accountType: 'payable',
        accountId: supplierId,
        amount: grandTotal,
        referenceType: 'return',
        referenceId: purchaseId,
        narration: `Debit note to supplier ${dnNumber}`,
        isAutoGenerated: true,
        createdBy,
      },
      session,
    );
  },

  async postVoucher({ storeId, voucherId, voucherType, voucherNumber, entries, narration, createdBy }, { session } = {}) {
    for (const e of entries) {
      await push(
        {
          storeId,
          entryType: e.entryType,
          accountType: e.accountType || 'journal',
          accountId: e.accountId,
          amount: Number(e.amount),
          referenceType: 'voucher',
          referenceId: voucherId,
          narration: narration || `${voucherType} ${voucherNumber}`,
          isAutoGenerated: false,
          createdBy,
        },
        session,
      );
    }
  },

  async verifyBalance(storeId) {
    const rows = await LedgerEntry.aggregate([
      { $match: { storeId: typeof storeId === 'string' ? require('mongoose').Types.ObjectId.createFromHexString(storeId) : storeId } },
      {
        $group: {
          _id: '$entryType',
          total: { $sum: '$amount' },
        },
      },
    ]);
    const debits = rows.find((r) => r._id === 'debit')?.total || 0;
    const credits = rows.find((r) => r._id === 'credit')?.total || 0;
    return { debits, credits, balanced: Math.abs(debits - credits) < 0.01 };
  },
};
