/**
 * PDF handling for the bill scanner.
 *
 * Two kinds of PDF arrive:
 *   1. DIGITAL  — generated by Tally / Zoho / Busy / etc. Has a real text
 *      layer. We read it directly → ~100% accurate, instant, no OCR.
 *   2. SCANNED  — a photo of paper saved as PDF. No usable text layer. We
 *      render each page to a high-DPI image so the OCR engine can read it.
 *
 * `extractPdf()` auto-detects which: it pulls the text layer, and if the
 * result is too sparse to be a real invoice (scanned PDFs return a few stray
 * characters at most), it falls back to rasterising the pages.
 *
 * pdfjs is dynamically imported so the ~1 MB library only loads when a user
 * actually scans a PDF.
 */

export interface PdfExtractResult {
  /** 'text' = read from the PDF's text layer; 'images' = rasterised for OCR. */
  kind: 'text' | 'images';
  /** Concatenated text when kind === 'text'. */
  text: string;
  /** Page canvases (as blobs) when kind === 'images', for the OCR step. */
  pageImages: Blob[];
  pageCount: number;
}

// A digital invoice's text layer has plenty of characters. Scanned PDFs
// usually yield only a handful of garbage glyphs (or none). Below this
// threshold we treat the PDF as image-only and rasterise instead.
const MIN_TEXT_CHARS_FOR_DIGITAL = 120;

// Render scale for the rasterise fallback. 3.0 gives OCR crisp glyph edges
// (the preprocessing then binarises) without ballooning memory at A4.
// Capped page count keeps big PDFs sane.
const RENDER_SCALE = 3.0;
const MAX_RENDER_PAGES = 8;

let workerConfigured = false;

async function loadPdfjs() {
  const pdfjs = await import('pdfjs-dist');
  if (!workerConfigured) {
    // Webpack (next dev/build --webpack) resolves this URL to a bundled asset.
    // Keeping the worker in-bundle avoids version-mismatch errors that a CDN
    // worker would risk.
    pdfjs.GlobalWorkerOptions.workerSrc = new URL(
      'pdfjs-dist/build/pdf.worker.min.mjs',
      import.meta.url,
    ).toString();
    workerConfigured = true;
  }
  return pdfjs;
}

async function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => (blob ? resolve(blob) : reject(new Error('canvas.toBlob returned null'))),
      'image/png',
    );
  });
}

export async function extractPdf(
  file: File,
  onProgress?: (msg: string, pct: number) => void,
): Promise<PdfExtractResult> {
  const pdfjs = await loadPdfjs();
  const buf = await file.arrayBuffer();
  const doc = await pdfjs.getDocument({ data: buf }).promise;
  const pageCount = doc.numPages;

  // --- Pass 1: try the text layer -----------------------------------------
  onProgress?.('reading-pdf-text', 0.1);
  let combined = '';
  for (let i = 1; i <= pageCount; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();
    // Join items with spaces; insert a newline when the y-position drops,
    // so the line-item parser sees row breaks rather than one long blob.
    let lastY: number | null = null;
    let lastXEnd: number | null = null;
    let pageText = '';
    for (const item of content.items as Array<{
      str: string; transform: number[]; width?: number;
    }>) {
      const x = item.transform?.[4];
      const y = item.transform?.[5];
      if (lastY !== null && typeof y === 'number' && Math.abs(y - lastY) > 2) {
        // New visual row.
        pageText += '\n';
        lastXEnd = null;
      } else if (
        lastXEnd !== null &&
        typeof x === 'number' &&
        x - lastXEnd > 12 // sizeable horizontal gap = a column break
      ) {
        // Preserve column separation with a double space so the line-item
        // parser can tell the description apart from the numeric columns.
        pageText += '  ';
      }
      pageText += item.str + ' ';
      if (typeof y === 'number') lastY = y;
      if (typeof x === 'number') lastXEnd = x + (item.width || 0);
    }
    combined += pageText + '\n';
    onProgress?.('reading-pdf-text', 0.1 + (0.4 * i) / pageCount);
  }

  if (combined.replace(/\s/g, '').length >= MIN_TEXT_CHARS_FOR_DIGITAL) {
    return { kind: 'text', text: combined, pageImages: [], pageCount };
  }

  // --- Pass 2: rasterise for OCR (scanned PDF) -----------------------------
  onProgress?.('rendering-pdf-pages', 0.5);
  const pageImages: Blob[] = [];
  const pagesToRender = Math.min(pageCount, MAX_RENDER_PAGES);
  for (let i = 1; i <= pagesToRender; i++) {
    const page = await doc.getPage(i);
    const viewport = page.getViewport({ scale: RENDER_SCALE });
    const canvas = document.createElement('canvas');
    canvas.width = Math.ceil(viewport.width);
    canvas.height = Math.ceil(viewport.height);
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Could not get 2D canvas context for PDF render');
    await page.render({ canvasContext: ctx, viewport }).promise;
    pageImages.push(await canvasToBlob(canvas));
    onProgress?.('rendering-pdf-pages', 0.5 + (0.4 * i) / pagesToRender);
  }

  return { kind: 'images', text: '', pageImages, pageCount };
}

export function isPdf(file: File): boolean {
  return file.type === 'application/pdf' || /\.pdf$/i.test(file.name);
}
