import mongoose from 'mongoose';

const ledgerEntrySchema = new mongoose.Schema(
  {
    storeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Store', required: true, index: true },
    entryType: { type: String, enum: ['debit', 'credit'], required: true },
    accountType: {
      type: String,
      enum: ['cash', 'bank', 'receivable', 'payable', 'revenue', 'expense', 'gst', 'journal'],
      required: true,
    },
    accountId: mongoose.Schema.Types.ObjectId,
    amount: { type: Number, required: true },
    balance: Number,
    referenceType: {
      type: String,
      enum: ['sale', 'purchase', 'payment', 'adjustment', 'journal', 'voucher', 'return', 'manual'],
    },
    referenceId: mongoose.Schema.Types.ObjectId,
    narration: String,
    isAutoGenerated: { type: Boolean, default: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

ledgerEntrySchema.index({ storeId: 1, accountType: 1, createdAt: -1 });
ledgerEntrySchema.index({ referenceId: 1, referenceType: 1 });
ledgerEntrySchema.index({ storeId: 1, accountId: 1, createdAt: 1 });

export const LedgerEntry = mongoose.models.LedgerEntry || mongoose.model('LedgerEntry', ledgerEntrySchema);
export default LedgerEntry;
