'use client';

import { Suspense, useEffect, useMemo, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { BookOpen, Download, RefreshCcw, Wallet, Banknote, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { api, ApiError } from '@/lib/api';

const money = (n: number) =>
  '₹' + Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

interface Account {
  _id: string;
  name: string;
  groupId: string;
  openingBalance: number;
}

interface LedgerEntry {
  _id: string;
  createdAt: string;
  entryType: 'debit' | 'credit';
  amount: number;
  referenceType: string;
  referenceId: string | null;
  narration: string;
  isAutoGenerated: boolean;
  runningBalance: number;
  runningBalanceType: 'Dr' | 'Cr';
}

interface LedgerResp {
  account: {
    _id: string;
    name: string;
    groupId: string;
    groupName: string;
    nature: 'asset' | 'liability' | 'income' | 'expense';
    openingBalance: number;
  };
  entries: LedgerEntry[];
  totals: {
    totalDebits: number;
    totalCredits: number;
    closingBalance: number;
    closingType: 'Dr' | 'Cr';
    opening: number;
  };
}

function ymd(d: Date) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function defaultRange() {
  const today = new Date();
  const start = new Date(today.getFullYear(), today.getMonth(), 1);
  return { from: ymd(start), to: ymd(today) };
}

function downloadCsv(filename: string, rows: (string | number)[][]) {
  const csv = rows
    .map((r) => r.map((v) => {
      const s = String(v ?? '');
      return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    }).join(','))
    .join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export default function LedgerPage() {
  return (
    <Suspense fallback={<div className="text-muted-foreground">Loading…</div>}>
      <LedgerInner />
    </Suspense>
  );
}

function LedgerInner() {
  const params = useSearchParams();
  const router = useRouter();
  const accountId = params.get('accountId');

  const [accounts, setAccounts] = useState<Account[]>([]);
  const [{ from, to }, setRange] = useState(defaultRange());
  const [data, setData] = useState<LedgerResp | null>(null);
  const [loading, setLoading] = useState(false);

  // Load chart of accounts once for the picker
  useEffect(() => {
    api.get<Account[]>('/accounting/accounts')
      .then(setAccounts)
      .catch(() => {});
  }, []);

  // Auto-pick a default account if none in URL: prefer Cash if it exists.
  useEffect(() => {
    if (accountId || accounts.length === 0) return;
    const cash = accounts.find((a) => a.name === 'Cash');
    const first = cash || accounts[0];
    if (first) router.replace(`/dashboard/ledger?accountId=${first._id}`);
  }, [accountId, accounts, router]);

  const load = async () => {
    if (!accountId) return;
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (from) params.set('from', from);
      if (to) params.set('to', `${to}T23:59:59`);
      setData(await api.get<LedgerResp>(`/accounting/accounts/${accountId}/ledger?${params}`));
    } catch (err) {
      if (err instanceof ApiError) toast.error(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (accountId) load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accountId, from, to]);

  const cashBank = useMemo(
    () => accounts.filter((a) => /cash|bank/i.test(a.name)),
    [accounts],
  );

  const exportCsv = () => {
    if (!data) return;
    const header = ['Date', 'Time', 'Type', 'Reference', 'Narration', 'Debit', 'Credit', 'Running balance', 'Dr/Cr'];
    const rows = data.entries.map((e) => {
      const d = new Date(e.createdAt);
      return [
        d.toLocaleDateString('en-IN'),
        d.toLocaleTimeString('en-IN'),
        e.entryType, e.referenceType, e.narration,
        e.entryType === 'debit' ? e.amount.toFixed(2) : '',
        e.entryType === 'credit' ? e.amount.toFixed(2) : '',
        e.runningBalance.toFixed(2), e.runningBalanceType,
      ];
    });
    downloadCsv(`ledger-${data.account.name.replace(/\s+/g, '-')}-${from}-to-${to}.csv`, [header, ...rows]);
    toast.success(`Exported ${data.entries.length} entries`);
  };

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <BookOpen className="w-7 h-7 text-blue-600" />
          Account Ledger
        </h1>
        <p className="text-muted-foreground mt-1">
          Drill-down view of every Dr / Cr posted to a single account, with running balance.
          Cash Book = Cash account · Bank Book = each Bank account.
        </p>
      </div>

      {cashBank.length > 0 && (
        <div className="flex flex-wrap gap-2 items-center">
          <span className="text-xs text-muted-foreground uppercase mr-1">Quick:</span>
          {cashBank.map((a) => (
            <Button
              key={a._id}
              size="sm"
              variant={accountId === a._id ? 'default' : 'outline'}
              onClick={() => router.push(`/dashboard/ledger?accountId=${a._id}`)}
              className={accountId === a._id ? 'bg-blue-600 hover:bg-blue-700' : ''}
            >
              {/cash/i.test(a.name) ? <Wallet className="w-3.5 h-3.5 mr-1" /> : <Banknote className="w-3.5 h-3.5 mr-1" />}
              {a.name}
            </Button>
          ))}
          <Button
            size="sm"
            variant="ghost"
            onClick={() => {
              const debtors = accounts.find((a) => a.name === 'Sundry Debtors');
              if (debtors) router.push(`/dashboard/ledger?accountId=${debtors._id}`);
            }}
            disabled={!accounts.find((a) => a.name === 'Sundry Debtors')}
          >
            <Sparkles className="w-3.5 h-3.5 mr-1" /> Sundry Debtors
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => {
              const creditors = accounts.find((a) => a.name === 'Sundry Creditors');
              if (creditors) router.push(`/dashboard/ledger?accountId=${creditors._id}`);
            }}
            disabled={!accounts.find((a) => a.name === 'Sundry Creditors')}
          >
            <Sparkles className="w-3.5 h-3.5 mr-1" /> Sundry Creditors
          </Button>
        </div>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-start justify-between gap-3 flex-wrap">
            <div>
              <CardTitle className="flex items-center gap-2">
                {data?.account.name || 'Pick an account'}
                {data && (
                  <Badge variant="outline" className="text-[10px]">
                    {data.account.groupName} · {data.account.nature}
                  </Badge>
                )}
              </CardTitle>
              <CardDescription>
                Period {new Date(from).toLocaleDateString('en-IN')} → {new Date(to).toLocaleDateString('en-IN')}
              </CardDescription>
            </div>
            <div className="flex flex-wrap gap-2 items-end">
              <div>
                <Label className="text-[10px] uppercase">Account</Label>
                <select
                  className="h-9 border rounded-md px-2 bg-background w-56"
                  value={accountId || ''}
                  onChange={(e) => router.push(`/dashboard/ledger?accountId=${e.target.value}`)}
                >
                  <option value="">— pick —</option>
                  {accounts.map((a) => (
                    <option key={a._id} value={a._id}>{a.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <Label className="text-[10px] uppercase">From</Label>
                <Input type="date" value={from} onChange={(e) => setRange({ from: e.target.value, to })} className="h-9 w-36" />
              </div>
              <div>
                <Label className="text-[10px] uppercase">To</Label>
                <Input type="date" value={to} onChange={(e) => setRange({ from, to: e.target.value })} className="h-9 w-36" />
              </div>
              <Button variant="outline" onClick={load} disabled={loading || !accountId}>
                <RefreshCcw className="w-4 h-4 mr-1" />{loading ? 'Loading…' : 'Refresh'}
              </Button>
              <Button onClick={exportCsv} disabled={!data || data.entries.length === 0} className="bg-blue-600 hover:bg-blue-700">
                <Download className="w-4 h-4 mr-1" /> Export CSV
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {data && (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs mb-3 bg-muted/40 rounded-md p-3">
              <Stat label="Opening" value={`${money(data.totals.opening)}`} />
              <Stat label="Total debits" value={money(data.totals.totalDebits)} bold />
              <Stat label="Total credits" value={money(data.totals.totalCredits)} bold />
              <Stat
                label="Closing"
                value={`${money(data.totals.closingBalance)} ${data.totals.closingType}`}
                bold
                tone={data.totals.closingType === 'Dr' ? 'emerald' : 'red'}
              />
            </div>
          )}

          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date / Time</TableHead>
                  <TableHead>Reference</TableHead>
                  <TableHead>Narration</TableHead>
                  <TableHead className="text-right">Debit</TableHead>
                  <TableHead className="text-right">Credit</TableHead>
                  <TableHead className="text-right">Running balance</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {!data || data.entries.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="text-center text-muted-foreground italic py-8">
                      {accountId ? 'No entries in this account for the selected period.' : 'Pick an account to view its ledger.'}
                    </TableCell>
                  </TableRow>
                ) : data.entries.map((e) => (
                  <TableRow key={e._id}>
                    <TableCell className="text-xs whitespace-nowrap">
                      <div>{new Date(e.createdAt).toLocaleDateString('en-IN')}</div>
                      <div className="text-[10px] text-muted-foreground">
                        {new Date(e.createdAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
                      </div>
                    </TableCell>
                    <TableCell>
                      {e.referenceType ? (
                        <Badge variant="secondary" className="text-[10px]">{e.referenceType}</Badge>
                      ) : '—'}
                    </TableCell>
                    <TableCell className="text-xs max-w-72 truncate" title={e.narration}>{e.narration || '—'}</TableCell>
                    <TableCell className="text-right font-mono">
                      {e.entryType === 'debit' ? money(e.amount) : ''}
                    </TableCell>
                    <TableCell className="text-right font-mono">
                      {e.entryType === 'credit' ? money(e.amount) : ''}
                    </TableCell>
                    <TableCell className="text-right font-mono">
                      <span className={e.runningBalanceType === 'Dr' ? 'text-emerald-600' : 'text-red-600'}>
                        {money(e.runningBalance)} {e.runningBalanceType}
                      </span>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function Stat({ label, value, bold, tone }: { label: string; value: string; bold?: boolean; tone?: 'emerald' | 'red' }) {
  const cls = tone === 'emerald' ? 'text-emerald-600' : tone === 'red' ? 'text-red-600' : '';
  return (
    <div>
      <div className="text-muted-foreground uppercase text-[10px]">{label}</div>
      <div className={`font-mono ${bold ? 'font-bold' : ''} ${cls}`}>{value}</div>
    </div>
  );
}
